### ISSUE TITLE
Suggestion on death award

### ISSUE THREAD

**Issue by forest0xia** [fretmute/fretbots#6]
before you added the dynamic difficulity, the death reward maybe a good/easier option to have to improve difficulty. But since you've added the dynamic difficulty, lets keep the tenets of DotA that we don't award death. Dota punishes death, so please consider setting the death award to be disabled by default.

**Comment by fretmute** [comment]
I feel this is mostly a matter of personal preference, and that's fine.  The entire point of the way that I set things up was to make it easy for folks to dial in settings as they please (mostly because the "balance", such as it is, is mostly me just guessing).  

In this case it's not really awarding death so much as punishing players that want to run up the score on the bots.  

I'm happy to suggest tweaks for folks that want local changes, however.
